# Generated by Django 4.1 on 2022-08-29 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psychowetpedia', '0007_delete_notatki'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notatki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_zwierzecia', models.CharField(blank=True, max_length=200, null=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('lek', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psychowetpedia.leki')),
                ('zaburzenie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psychowetpedia.zaburzenia')),
            ],
        ),
    ]
