# Generated by Django 4.1 on 2022-09-03 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notatki_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notatki',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
