# Generated by Django 4.1 on 2022-09-03 09:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220903_1149'),
    ]

    operations = [migrations.AlterField(
            model_name='notatki',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
