# Generated by Django 4.1 on 2022-08-20 12:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leki',
            fields=[
                ('nazwa', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('mechanizm', models.TextField(blank=True, null=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('przeciwwskazania', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zaburzenia',
            fields=[
                ('nazwa', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dawka_pies', models.CharField(blank=True, max_length=200, null=True)),
                ('dawka_kot', models.CharField(blank=True, max_length=200, null=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('lek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychowetpedia.leki')),
                ('zaburzenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychowetpedia.zaburzenia')),
            ],
        ),
    ]
