# Generated by Django 4.1 on 2022-08-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychowetpedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaburzenia',
            name='spec_gat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
