# Generated by Django 4.1 on 2022-08-24 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('psychowetpedia', '0004_auto_20220824_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leki',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='zaburzenia',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
