# Generated by Django 4.1 on 2022-08-29 14:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('psychowetpedia', '0005_auto_20220824_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leki',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='zaburzenia',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='Notatki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_zwierzecia', models.CharField(blank=True, max_length=200, null=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('lek', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psychowetpedia.leki')),
                ('zaburzenie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psychowetpedia.zaburzenia')),
            ],
        ),
    ]
