# Generated by Django 4.1 on 2022-08-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychowetpedia', '0006_alter_leki_uuid_alter_zaburzenia_uuid_notatki'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notatki',
        ),
    ]
